//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("ti2Model", "fk_Administrador_Condominio1", "Condominio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Condominio), "Administrador", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Administrador), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Estacionamiento_Condominio", "Condominio", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Condominio), "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Estacionamiento), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Estac_Persona_Estacionamiento1", "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Estacionamiento), "Estac_Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Estac_Persona), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Estac_Persona_Propietario1", "Propietario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Propietario), "Estac_Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Estac_Persona), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Notificacion_Estacionamiento1", "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Estacionamiento), "Notificacion", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Notificacion), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Visita_Estacionamiento1", "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Owl_Parking.Estacionamiento), "Visita", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Visita), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "FK__Estacionamiento", "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Owl_Parking.Estacionamiento), "Arduino", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Arduino), true)]
[assembly: EdmRelationshipAttribute("ti2Model", "fk_Estacionamiento_Arduino", "Arduino", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(Owl_Parking.Arduino), "Estacionamiento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Owl_Parking.Estacionamiento), true)]

#endregion

namespace Owl_Parking
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class ti2Entities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto ti2Entities usando la cadena de conexión encontrada en la sección 'ti2Entities' del archivo de configuración de la aplicación.
        /// </summary>
        public ti2Entities() : base("name=ti2Entities", "ti2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ti2Entities.
        /// </summary>
        public ti2Entities(string connectionString) : base(connectionString, "ti2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto ti2Entities.
        /// </summary>
        public ti2Entities(EntityConnection connection) : base(connection, "ti2Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Administrador> Administrador
        {
            get
            {
                if ((_Administrador == null))
                {
                    _Administrador = base.CreateObjectSet<Administrador>("Administrador");
                }
                return _Administrador;
            }
        }
        private ObjectSet<Administrador> _Administrador;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Condominio> Condominio
        {
            get
            {
                if ((_Condominio == null))
                {
                    _Condominio = base.CreateObjectSet<Condominio>("Condominio");
                }
                return _Condominio;
            }
        }
        private ObjectSet<Condominio> _Condominio;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Estac_Persona> Estac_Persona
        {
            get
            {
                if ((_Estac_Persona == null))
                {
                    _Estac_Persona = base.CreateObjectSet<Estac_Persona>("Estac_Persona");
                }
                return _Estac_Persona;
            }
        }
        private ObjectSet<Estac_Persona> _Estac_Persona;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Estacionamiento> Estacionamiento
        {
            get
            {
                if ((_Estacionamiento == null))
                {
                    _Estacionamiento = base.CreateObjectSet<Estacionamiento>("Estacionamiento");
                }
                return _Estacionamiento;
            }
        }
        private ObjectSet<Estacionamiento> _Estacionamiento;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Notificacion> Notificacion
        {
            get
            {
                if ((_Notificacion == null))
                {
                    _Notificacion = base.CreateObjectSet<Notificacion>("Notificacion");
                }
                return _Notificacion;
            }
        }
        private ObjectSet<Notificacion> _Notificacion;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Propietario> Propietario
        {
            get
            {
                if ((_Propietario == null))
                {
                    _Propietario = base.CreateObjectSet<Propietario>("Propietario");
                }
                return _Propietario;
            }
        }
        private ObjectSet<Propietario> _Propietario;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Visita> Visita
        {
            get
            {
                if ((_Visita == null))
                {
                    _Visita = base.CreateObjectSet<Visita>("Visita");
                }
                return _Visita;
            }
        }
        private ObjectSet<Visita> _Visita;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Arduino> Arduino
        {
            get
            {
                if ((_Arduino == null))
                {
                    _Arduino = base.CreateObjectSet<Arduino>("Arduino");
                }
                return _Arduino;
            }
        }
        private ObjectSet<Arduino> _Arduino;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Administrador. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToAdministrador(Administrador administrador)
        {
            base.AddObject("Administrador", administrador);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Condominio. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToCondominio(Condominio condominio)
        {
            base.AddObject("Condominio", condominio);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Estac_Persona. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstac_Persona(Estac_Persona estac_Persona)
        {
            base.AddObject("Estac_Persona", estac_Persona);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Estacionamiento. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEstacionamiento(Estacionamiento estacionamiento)
        {
            base.AddObject("Estacionamiento", estacionamiento);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Notificacion. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToNotificacion(Notificacion notificacion)
        {
            base.AddObject("Notificacion", notificacion);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Propietario. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPropietario(Propietario propietario)
        {
            base.AddObject("Propietario", propietario);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Visita. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToVisita(Visita visita)
        {
            base.AddObject("Visita", visita);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Arduino. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToArduino(Arduino arduino)
        {
            base.AddObject("Arduino", arduino);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Administrador")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Administrador : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Administrador.
        /// </summary>
        /// <param name="administrador_Id">Valor inicial de la propiedad Administrador_Id.</param>
        /// <param name="condominio_Id">Valor inicial de la propiedad Condominio_Id.</param>
        public static Administrador CreateAdministrador(global::System.Int32 administrador_Id, global::System.Int32 condominio_Id)
        {
            Administrador administrador = new Administrador();
            administrador.Administrador_Id = administrador_Id;
            administrador.Condominio_Id = condominio_Id;
            return administrador;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Administrador_Id
        {
            get
            {
                return _Administrador_Id;
            }
            set
            {
                if (_Administrador_Id != value)
                {
                    OnAdministrador_IdChanging(value);
                    ReportPropertyChanging("Administrador_Id");
                    _Administrador_Id = StructuralObject.SetValidValue(value, "Administrador_Id");
                    ReportPropertyChanged("Administrador_Id");
                    OnAdministrador_IdChanged();
                }
            }
        }
        private global::System.Int32 _Administrador_Id;
        partial void OnAdministrador_IdChanging(global::System.Int32 value);
        partial void OnAdministrador_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true, "Correo");
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Cargo
        {
            get
            {
                return _Cargo;
            }
            set
            {
                OnCargoChanging(value);
                ReportPropertyChanging("Cargo");
                _Cargo = StructuralObject.SetValidValue(value, true, "Cargo");
                ReportPropertyChanged("Cargo");
                OnCargoChanged();
            }
        }
        private global::System.String _Cargo;
        partial void OnCargoChanging(global::System.String value);
        partial void OnCargoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Condominio_Id
        {
            get
            {
                return _Condominio_Id;
            }
            set
            {
                OnCondominio_IdChanging(value);
                ReportPropertyChanging("Condominio_Id");
                _Condominio_Id = StructuralObject.SetValidValue(value, "Condominio_Id");
                ReportPropertyChanged("Condominio_Id");
                OnCondominio_IdChanged();
            }
        }
        private global::System.Int32 _Condominio_Id;
        partial void OnCondominio_IdChanging(global::System.Int32 value);
        partial void OnCondominio_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Administrador_Condominio1", "Condominio")]
        public Condominio Condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Administrador_Condominio1", "Condominio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Administrador_Condominio1", "Condominio").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Condominio> CondominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Administrador_Condominio1", "Condominio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Condominio>("ti2Model.fk_Administrador_Condominio1", "Condominio", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Arduino")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Arduino : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Arduino.
        /// </summary>
        /// <param name="arduino_Id">Valor inicial de la propiedad Arduino_Id.</param>
        public static Arduino CreateArduino(global::System.Int32 arduino_Id)
        {
            Arduino arduino = new Arduino();
            arduino.Arduino_Id = arduino_Id;
            return arduino;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Arduino_Id
        {
            get
            {
                return _Arduino_Id;
            }
            set
            {
                if (_Arduino_Id != value)
                {
                    OnArduino_IdChanging(value);
                    ReportPropertyChanging("Arduino_Id");
                    _Arduino_Id = StructuralObject.SetValidValue(value, "Arduino_Id");
                    ReportPropertyChanged("Arduino_Id");
                    OnArduino_IdChanged();
                }
            }
        }
        private global::System.Int32 _Arduino_Id;
        partial void OnArduino_IdChanging(global::System.Int32 value);
        partial void OnArduino_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private Nullable<global::System.Int32> _Estado;
        partial void OnEstadoChanging(Nullable<global::System.Int32> value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Estacionamiento_Id
        {
            get
            {
                return _Estacionamiento_Id;
            }
            set
            {
                OnEstacionamiento_IdChanging(value);
                ReportPropertyChanging("Estacionamiento_Id");
                _Estacionamiento_Id = StructuralObject.SetValidValue(value, "Estacionamiento_Id");
                ReportPropertyChanged("Estacionamiento_Id");
                OnEstacionamiento_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Estacionamiento_Id;
        partial void OnEstacionamiento_IdChanging(Nullable<global::System.Int32> value);
        partial void OnEstacionamiento_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "FK__Estacionamiento", "Estacionamiento")]
        public Estacionamiento Estacionamiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.FK__Estacionamiento", "Estacionamiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.FK__Estacionamiento", "Estacionamiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estacionamiento> EstacionamientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.FK__Estacionamiento", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estacionamiento>("ti2Model.FK__Estacionamiento", "Estacionamiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estacionamiento_Arduino", "Estacionamiento")]
        public EntityCollection<Estacionamiento> Estacionamiento1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Estacionamiento>("ti2Model.fk_Estacionamiento_Arduino", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Estacionamiento>("ti2Model.fk_Estacionamiento_Arduino", "Estacionamiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Condominio")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Condominio : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Condominio.
        /// </summary>
        /// <param name="condominio_Id">Valor inicial de la propiedad Condominio_Id.</param>
        public static Condominio CreateCondominio(global::System.Int32 condominio_Id)
        {
            Condominio condominio = new Condominio();
            condominio.Condominio_Id = condominio_Id;
            return condominio;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Condominio_Id
        {
            get
            {
                return _Condominio_Id;
            }
            set
            {
                if (_Condominio_Id != value)
                {
                    OnCondominio_IdChanging(value);
                    ReportPropertyChanging("Condominio_Id");
                    _Condominio_Id = StructuralObject.SetValidValue(value, "Condominio_Id");
                    ReportPropertyChanged("Condominio_Id");
                    OnCondominio_IdChanged();
                }
            }
        }
        private global::System.Int32 _Condominio_Id;
        partial void OnCondominio_IdChanging(global::System.Int32 value);
        partial void OnCondominio_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Administrador_Condominio1", "Administrador")]
        public EntityCollection<Administrador> Administrador
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Administrador>("ti2Model.fk_Administrador_Condominio1", "Administrador");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Administrador>("ti2Model.fk_Administrador_Condominio1", "Administrador", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estacionamiento_Condominio", "Estacionamiento")]
        public EntityCollection<Estacionamiento> Estacionamiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Estacionamiento>("ti2Model.fk_Estacionamiento_Condominio", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Estacionamiento>("ti2Model.fk_Estacionamiento_Condominio", "Estacionamiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Estac_Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estac_Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Estac_Persona.
        /// </summary>
        /// <param name="estac_Persona_Id">Valor inicial de la propiedad Estac_Persona_Id.</param>
        /// <param name="estacionamiento_Id">Valor inicial de la propiedad Estacionamiento_Id.</param>
        /// <param name="propietario_Id">Valor inicial de la propiedad Propietario_Id.</param>
        public static Estac_Persona CreateEstac_Persona(global::System.Int32 estac_Persona_Id, global::System.Int32 estacionamiento_Id, global::System.Int32 propietario_Id)
        {
            Estac_Persona estac_Persona = new Estac_Persona();
            estac_Persona.Estac_Persona_Id = estac_Persona_Id;
            estac_Persona.Estacionamiento_Id = estacionamiento_Id;
            estac_Persona.Propietario_Id = propietario_Id;
            return estac_Persona;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estac_Persona_Id
        {
            get
            {
                return _Estac_Persona_Id;
            }
            set
            {
                if (_Estac_Persona_Id != value)
                {
                    OnEstac_Persona_IdChanging(value);
                    ReportPropertyChanging("Estac_Persona_Id");
                    _Estac_Persona_Id = StructuralObject.SetValidValue(value, "Estac_Persona_Id");
                    ReportPropertyChanged("Estac_Persona_Id");
                    OnEstac_Persona_IdChanged();
                }
            }
        }
        private global::System.Int32 _Estac_Persona_Id;
        partial void OnEstac_Persona_IdChanging(global::System.Int32 value);
        partial void OnEstac_Persona_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estacionamiento_Id
        {
            get
            {
                return _Estacionamiento_Id;
            }
            set
            {
                OnEstacionamiento_IdChanging(value);
                ReportPropertyChanging("Estacionamiento_Id");
                _Estacionamiento_Id = StructuralObject.SetValidValue(value, "Estacionamiento_Id");
                ReportPropertyChanged("Estacionamiento_Id");
                OnEstacionamiento_IdChanged();
            }
        }
        private global::System.Int32 _Estacionamiento_Id;
        partial void OnEstacionamiento_IdChanging(global::System.Int32 value);
        partial void OnEstacionamiento_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Propietario_Id
        {
            get
            {
                return _Propietario_Id;
            }
            set
            {
                OnPropietario_IdChanging(value);
                ReportPropertyChanging("Propietario_Id");
                _Propietario_Id = StructuralObject.SetValidValue(value, "Propietario_Id");
                ReportPropertyChanged("Propietario_Id");
                OnPropietario_IdChanged();
            }
        }
        private global::System.Int32 _Propietario_Id;
        partial void OnPropietario_IdChanging(global::System.Int32 value);
        partial void OnPropietario_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estac_Persona_Estacionamiento1", "Estacionamiento")]
        public Estacionamiento Estacionamiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estacionamiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estacionamiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estacionamiento> EstacionamientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estacionamiento>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estacionamiento", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estac_Persona_Propietario1", "Propietario")]
        public Propietario Propietario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Propietario>("ti2Model.fk_Estac_Persona_Propietario1", "Propietario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Propietario>("ti2Model.fk_Estac_Persona_Propietario1", "Propietario").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Propietario> PropietarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Propietario>("ti2Model.fk_Estac_Persona_Propietario1", "Propietario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Propietario>("ti2Model.fk_Estac_Persona_Propietario1", "Propietario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Estacionamiento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Estacionamiento : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Estacionamiento.
        /// </summary>
        /// <param name="estacionamiento_Id">Valor inicial de la propiedad Estacionamiento_Id.</param>
        /// <param name="condominio_Id">Valor inicial de la propiedad Condominio_Id.</param>
        public static Estacionamiento CreateEstacionamiento(global::System.Int32 estacionamiento_Id, global::System.Int32 condominio_Id)
        {
            Estacionamiento estacionamiento = new Estacionamiento();
            estacionamiento.Estacionamiento_Id = estacionamiento_Id;
            estacionamiento.Condominio_Id = condominio_Id;
            return estacionamiento;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estacionamiento_Id
        {
            get
            {
                return _Estacionamiento_Id;
            }
            set
            {
                if (_Estacionamiento_Id != value)
                {
                    OnEstacionamiento_IdChanging(value);
                    ReportPropertyChanging("Estacionamiento_Id");
                    _Estacionamiento_Id = StructuralObject.SetValidValue(value, "Estacionamiento_Id");
                    ReportPropertyChanged("Estacionamiento_Id");
                    OnEstacionamiento_IdChanged();
                }
            }
        }
        private global::System.Int32 _Estacionamiento_Id;
        partial void OnEstacionamiento_IdChanging(global::System.Int32 value);
        partial void OnEstacionamiento_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Estado
        {
            get
            {
                return _Estado;
            }
            set
            {
                OnEstadoChanging(value);
                ReportPropertyChanging("Estado");
                _Estado = StructuralObject.SetValidValue(value, true, "Estado");
                ReportPropertyChanged("Estado");
                OnEstadoChanged();
            }
        }
        private global::System.String _Estado;
        partial void OnEstadoChanging(global::System.String value);
        partial void OnEstadoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tipo
        {
            get
            {
                return _Tipo;
            }
            set
            {
                OnTipoChanging(value);
                ReportPropertyChanging("Tipo");
                _Tipo = StructuralObject.SetValidValue(value, true, "Tipo");
                ReportPropertyChanged("Tipo");
                OnTipoChanged();
            }
        }
        private global::System.String _Tipo;
        partial void OnTipoChanging(global::System.String value);
        partial void OnTipoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Codigo
        {
            get
            {
                return _Codigo;
            }
            set
            {
                OnCodigoChanging(value);
                ReportPropertyChanging("Codigo");
                _Codigo = StructuralObject.SetValidValue(value, true, "Codigo");
                ReportPropertyChanged("Codigo");
                OnCodigoChanged();
            }
        }
        private global::System.String _Codigo;
        partial void OnCodigoChanging(global::System.String value);
        partial void OnCodigoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Condominio_Id
        {
            get
            {
                return _Condominio_Id;
            }
            set
            {
                OnCondominio_IdChanging(value);
                ReportPropertyChanging("Condominio_Id");
                _Condominio_Id = StructuralObject.SetValidValue(value, "Condominio_Id");
                ReportPropertyChanged("Condominio_Id");
                OnCondominio_IdChanged();
            }
        }
        private global::System.Int32 _Condominio_Id;
        partial void OnCondominio_IdChanging(global::System.Int32 value);
        partial void OnCondominio_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Arduino_Id
        {
            get
            {
                return _Arduino_Id;
            }
            set
            {
                OnArduino_IdChanging(value);
                ReportPropertyChanging("Arduino_Id");
                _Arduino_Id = StructuralObject.SetValidValue(value, "Arduino_Id");
                ReportPropertyChanged("Arduino_Id");
                OnArduino_IdChanged();
            }
        }
        private Nullable<global::System.Int32> _Arduino_Id;
        partial void OnArduino_IdChanging(Nullable<global::System.Int32> value);
        partial void OnArduino_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estacionamiento_Condominio", "Condominio")]
        public Condominio Condominio
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Estacionamiento_Condominio", "Condominio").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Estacionamiento_Condominio", "Condominio").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Condominio> CondominioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Condominio>("ti2Model.fk_Estacionamiento_Condominio", "Condominio");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Condominio>("ti2Model.fk_Estacionamiento_Condominio", "Condominio", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estac_Persona_Estacionamiento1", "Estac_Persona")]
        public EntityCollection<Estac_Persona> Estac_Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Estac_Persona>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estac_Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Estac_Persona>("ti2Model.fk_Estac_Persona_Estacionamiento1", "Estac_Persona", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Notificacion_Estacionamiento1", "Notificacion")]
        public EntityCollection<Notificacion> Notificacion
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Notificacion>("ti2Model.fk_Notificacion_Estacionamiento1", "Notificacion");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Notificacion>("ti2Model.fk_Notificacion_Estacionamiento1", "Notificacion", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Visita_Estacionamiento1", "Visita")]
        public EntityCollection<Visita> Visita
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Visita>("ti2Model.fk_Visita_Estacionamiento1", "Visita");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Visita>("ti2Model.fk_Visita_Estacionamiento1", "Visita", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "FK__Estacionamiento", "Arduino")]
        public EntityCollection<Arduino> Arduino
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Arduino>("ti2Model.FK__Estacionamiento", "Arduino");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Arduino>("ti2Model.FK__Estacionamiento", "Arduino", value);
                }
            }
        }
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estacionamiento_Arduino", "Arduino")]
        public Arduino Arduino1
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Arduino>("ti2Model.fk_Estacionamiento_Arduino", "Arduino").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Arduino>("ti2Model.fk_Estacionamiento_Arduino", "Arduino").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Arduino> Arduino1Reference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Arduino>("ti2Model.fk_Estacionamiento_Arduino", "Arduino");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Arduino>("ti2Model.fk_Estacionamiento_Arduino", "Arduino", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Notificacion")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Notificacion : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Notificacion.
        /// </summary>
        /// <param name="notificacion_Id">Valor inicial de la propiedad Notificacion_Id.</param>
        /// <param name="estacionamiento_Id">Valor inicial de la propiedad Estacionamiento_Id.</param>
        public static Notificacion CreateNotificacion(global::System.Int32 notificacion_Id, global::System.Int32 estacionamiento_Id)
        {
            Notificacion notificacion = new Notificacion();
            notificacion.Notificacion_Id = notificacion_Id;
            notificacion.Estacionamiento_Id = estacionamiento_Id;
            return notificacion;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Notificacion_Id
        {
            get
            {
                return _Notificacion_Id;
            }
            set
            {
                if (_Notificacion_Id != value)
                {
                    OnNotificacion_IdChanging(value);
                    ReportPropertyChanging("Notificacion_Id");
                    _Notificacion_Id = StructuralObject.SetValidValue(value, "Notificacion_Id");
                    ReportPropertyChanged("Notificacion_Id");
                    OnNotificacion_IdChanged();
                }
            }
        }
        private global::System.Int32 _Notificacion_Id;
        partial void OnNotificacion_IdChanging(global::System.Int32 value);
        partial void OnNotificacion_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Fecha
        {
            get
            {
                return _Fecha;
            }
            set
            {
                OnFechaChanging(value);
                ReportPropertyChanging("Fecha");
                _Fecha = StructuralObject.SetValidValue(value, "Fecha");
                ReportPropertyChanged("Fecha");
                OnFechaChanged();
            }
        }
        private Nullable<global::System.DateTime> _Fecha;
        partial void OnFechaChanging(Nullable<global::System.DateTime> value);
        partial void OnFechaChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Comentario
        {
            get
            {
                return _Comentario;
            }
            set
            {
                OnComentarioChanging(value);
                ReportPropertyChanging("Comentario");
                _Comentario = StructuralObject.SetValidValue(value, true, "Comentario");
                ReportPropertyChanged("Comentario");
                OnComentarioChanged();
            }
        }
        private global::System.String _Comentario;
        partial void OnComentarioChanging(global::System.String value);
        partial void OnComentarioChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estacionamiento_Id
        {
            get
            {
                return _Estacionamiento_Id;
            }
            set
            {
                OnEstacionamiento_IdChanging(value);
                ReportPropertyChanging("Estacionamiento_Id");
                _Estacionamiento_Id = StructuralObject.SetValidValue(value, "Estacionamiento_Id");
                ReportPropertyChanged("Estacionamiento_Id");
                OnEstacionamiento_IdChanged();
            }
        }
        private global::System.Int32 _Estacionamiento_Id;
        partial void OnEstacionamiento_IdChanging(global::System.Int32 value);
        partial void OnEstacionamiento_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Notificacion_Estacionamiento1", "Estacionamiento")]
        public Estacionamiento Estacionamiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Notificacion_Estacionamiento1", "Estacionamiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Notificacion_Estacionamiento1", "Estacionamiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estacionamiento> EstacionamientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Notificacion_Estacionamiento1", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estacionamiento>("ti2Model.fk_Notificacion_Estacionamiento1", "Estacionamiento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Propietario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Propietario : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Propietario.
        /// </summary>
        /// <param name="propietario_Id">Valor inicial de la propiedad Propietario_Id.</param>
        public static Propietario CreatePropietario(global::System.Int32 propietario_Id)
        {
            Propietario propietario = new Propietario();
            propietario.Propietario_Id = propietario_Id;
            return propietario;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Propietario_Id
        {
            get
            {
                return _Propietario_Id;
            }
            set
            {
                if (_Propietario_Id != value)
                {
                    OnPropietario_IdChanging(value);
                    ReportPropertyChanging("Propietario_Id");
                    _Propietario_Id = StructuralObject.SetValidValue(value, "Propietario_Id");
                    ReportPropertyChanged("Propietario_Id");
                    OnPropietario_IdChanged();
                }
            }
        }
        private global::System.Int32 _Propietario_Id;
        partial void OnPropietario_IdChanging(global::System.Int32 value);
        partial void OnPropietario_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                OnPatenteChanging(value);
                ReportPropertyChanging("Patente");
                _Patente = StructuralObject.SetValidValue(value, true, "Patente");
                ReportPropertyChanged("Patente");
                OnPatenteChanged();
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Torre
        {
            get
            {
                return _Torre;
            }
            set
            {
                OnTorreChanging(value);
                ReportPropertyChanging("Torre");
                _Torre = StructuralObject.SetValidValue(value, true, "Torre");
                ReportPropertyChanged("Torre");
                OnTorreChanged();
            }
        }
        private global::System.String _Torre;
        partial void OnTorreChanging(global::System.String value);
        partial void OnTorreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Departamento
        {
            get
            {
                return _Departamento;
            }
            set
            {
                OnDepartamentoChanging(value);
                ReportPropertyChanging("Departamento");
                _Departamento = StructuralObject.SetValidValue(value, true, "Departamento");
                ReportPropertyChanged("Departamento");
                OnDepartamentoChanged();
            }
        }
        private global::System.String _Departamento;
        partial void OnDepartamentoChanging(global::System.String value);
        partial void OnDepartamentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true, "Correo");
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Password
        {
            get
            {
                return _Password;
            }
            set
            {
                OnPasswordChanging(value);
                ReportPropertyChanging("Password");
                _Password = StructuralObject.SetValidValue(value, true, "Password");
                ReportPropertyChanged("Password");
                OnPasswordChanged();
            }
        }
        private global::System.String _Password;
        partial void OnPasswordChanging(global::System.String value);
        partial void OnPasswordChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Estac_Persona_Propietario1", "Estac_Persona")]
        public EntityCollection<Estac_Persona> Estac_Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Estac_Persona>("ti2Model.fk_Estac_Persona_Propietario1", "Estac_Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Estac_Persona>("ti2Model.fk_Estac_Persona_Propietario1", "Estac_Persona", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="ti2Model", Name="Visita")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Visita : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Visita.
        /// </summary>
        /// <param name="visita_Id">Valor inicial de la propiedad Visita_Id.</param>
        /// <param name="estacionamiento_Id">Valor inicial de la propiedad Estacionamiento_Id.</param>
        public static Visita CreateVisita(global::System.Int32 visita_Id, global::System.Int32 estacionamiento_Id)
        {
            Visita visita = new Visita();
            visita.Visita_Id = visita_Id;
            visita.Estacionamiento_Id = estacionamiento_Id;
            return visita;
        }

        #endregion

        #region Propiedades simples
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Visita_Id
        {
            get
            {
                return _Visita_Id;
            }
            set
            {
                if (_Visita_Id != value)
                {
                    OnVisita_IdChanging(value);
                    ReportPropertyChanging("Visita_Id");
                    _Visita_Id = StructuralObject.SetValidValue(value, "Visita_Id");
                    ReportPropertyChanged("Visita_Id");
                    OnVisita_IdChanged();
                }
            }
        }
        private global::System.Int32 _Visita_Id;
        partial void OnVisita_IdChanging(global::System.Int32 value);
        partial void OnVisita_IdChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, true, "Nombre");
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Patente
        {
            get
            {
                return _Patente;
            }
            set
            {
                OnPatenteChanging(value);
                ReportPropertyChanging("Patente");
                _Patente = StructuralObject.SetValidValue(value, true, "Patente");
                ReportPropertyChanged("Patente");
                OnPatenteChanged();
            }
        }
        private global::System.String _Patente;
        partial void OnPatenteChanging(global::System.String value);
        partial void OnPatenteChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true, "Telefono");
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Torre
        {
            get
            {
                return _Torre;
            }
            set
            {
                OnTorreChanging(value);
                ReportPropertyChanging("Torre");
                _Torre = StructuralObject.SetValidValue(value, true, "Torre");
                ReportPropertyChanged("Torre");
                OnTorreChanged();
            }
        }
        private global::System.String _Torre;
        partial void OnTorreChanging(global::System.String value);
        partial void OnTorreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Departamento
        {
            get
            {
                return _Departamento;
            }
            set
            {
                OnDepartamentoChanging(value);
                ReportPropertyChanging("Departamento");
                _Departamento = StructuralObject.SetValidValue(value, true, "Departamento");
                ReportPropertyChanged("Departamento");
                OnDepartamentoChanged();
            }
        }
        private global::System.String _Departamento;
        partial void OnDepartamentoChanging(global::System.String value);
        partial void OnDepartamentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Hora
        {
            get
            {
                return _Hora;
            }
            set
            {
                OnHoraChanging(value);
                ReportPropertyChanging("Hora");
                _Hora = StructuralObject.SetValidValue(value, "Hora");
                ReportPropertyChanged("Hora");
                OnHoraChanged();
            }
        }
        private Nullable<global::System.DateTime> _Hora;
        partial void OnHoraChanging(Nullable<global::System.DateTime> value);
        partial void OnHoraChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Estacionamiento_Id
        {
            get
            {
                return _Estacionamiento_Id;
            }
            set
            {
                OnEstacionamiento_IdChanging(value);
                ReportPropertyChanging("Estacionamiento_Id");
                _Estacionamiento_Id = StructuralObject.SetValidValue(value, "Estacionamiento_Id");
                ReportPropertyChanged("Estacionamiento_Id");
                OnEstacionamiento_IdChanged();
            }
        }
        private global::System.Int32 _Estacionamiento_Id;
        partial void OnEstacionamiento_IdChanging(global::System.Int32 value);
        partial void OnEstacionamiento_IdChanged();

        #endregion

        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("ti2Model", "fk_Visita_Estacionamiento1", "Estacionamiento")]
        public Estacionamiento Estacionamiento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Visita_Estacionamiento1", "Estacionamiento").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Visita_Estacionamiento1", "Estacionamiento").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Estacionamiento> EstacionamientoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Estacionamiento>("ti2Model.fk_Visita_Estacionamiento1", "Estacionamiento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Estacionamiento>("ti2Model.fk_Visita_Estacionamiento1", "Estacionamiento", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
